// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: authors.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countAuthors = `-- name: CountAuthors :one
SELECT COUNT(*) FROM authors
`

func (q *Queries) CountAuthors(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAuthors)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAuthorsSearch = `-- name: CountAuthorsSearch :one
SELECT COUNT(*) FROM authors
WHERE name ILIKE '%' || $1 || '%'
`

func (q *Queries) CountAuthorsSearch(ctx context.Context, dollar_1 *string) (int64, error) {
	row := q.db.QueryRow(ctx, countAuthorsSearch, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthor = `-- name: CreateAuthor :one
INSERT INTO authors (name, slug, bio)
VALUES ($1, $2, $3)
RETURNING id, name, slug, bio, created_at, updated_at
`

type CreateAuthorParams struct {
	Name string
	Slug *string
	Bio  *string
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error) {
	row := q.db.QueryRow(ctx, createAuthor, arg.Name, arg.Slug, arg.Bio)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAuthor = `-- name: DeleteAuthor :exec
DELETE FROM authors WHERE id = $1
`

func (q *Queries) DeleteAuthor(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAuthor, id)
	return err
}

const getAuthorBookCount = `-- name: GetAuthorBookCount :one
SELECT COUNT(*) FROM books WHERE author_id = $1
`

func (q *Queries) GetAuthorBookCount(ctx context.Context, authorID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getAuthorBookCount, authorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAuthorByID = `-- name: GetAuthorByID :one
SELECT id, name, slug, bio, created_at, updated_at FROM authors WHERE id = $1
`

func (q *Queries) GetAuthorByID(ctx context.Context, id uuid.UUID) (Author, error) {
	row := q.db.QueryRow(ctx, getAuthorByID, id)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthorByName = `-- name: GetAuthorByName :one
SELECT id, name, slug, bio, created_at, updated_at FROM authors WHERE name = $1
`

func (q *Queries) GetAuthorByName(ctx context.Context, name string) (Author, error) {
	row := q.db.QueryRow(ctx, getAuthorByName, name)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthorBySlug = `-- name: GetAuthorBySlug :one
SELECT id, name, slug, bio, created_at, updated_at FROM authors WHERE slug = $1
`

func (q *Queries) GetAuthorBySlug(ctx context.Context, slug *string) (Author, error) {
	row := q.db.QueryRow(ctx, getAuthorBySlug, slug)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAuthors = `-- name: ListAuthors :many
SELECT id, name, slug, bio, created_at, updated_at FROM authors
ORDER BY name
LIMIT $1 OFFSET $2
`

type ListAuthorsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAuthors(ctx context.Context, arg ListAuthorsParams) ([]Author, error) {
	rows, err := q.db.Query(ctx, listAuthors, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Author
	for rows.Next() {
		var i Author
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Bio,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAuthors = `-- name: SearchAuthors :many
SELECT id, name, slug, bio, created_at, updated_at FROM authors
WHERE name ILIKE '%' || $1 || '%'
ORDER BY name
LIMIT $2 OFFSET $3
`

type SearchAuthorsParams struct {
	Column1 *string
	Limit   int32
	Offset  int32
}

func (q *Queries) SearchAuthors(ctx context.Context, arg SearchAuthorsParams) ([]Author, error) {
	rows, err := q.db.Query(ctx, searchAuthors, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Author
	for rows.Next() {
		var i Author
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Bio,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAuthor = `-- name: UpdateAuthor :one
UPDATE authors
SET name = $2, slug = $3, bio = $4, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, slug, bio, created_at, updated_at
`

type UpdateAuthorParams struct {
	ID   uuid.UUID
	Name string
	Slug *string
	Bio  *string
}

func (q *Queries) UpdateAuthor(ctx context.Context, arg UpdateAuthorParams) (Author, error) {
	row := q.db.QueryRow(ctx, updateAuthor,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Bio,
	)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
