// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: books.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countSearchResults = `-- name: CountSearchResults :one
SELECT COUNT(*) as total
FROM books
WHERE 
  ($1::text IS NULL OR title ILIKE '%' || $1 || '%')
  AND ($2::text IS NULL OR author ILIKE '%' || $2 || '%')
  AND ($3::text IS NULL OR publisher ILIKE '%' || $3 || '%')
  AND ($4::text IS NULL OR series_name ILIKE '%' || $4 || '%')
`

type CountSearchResultsParams struct {
	Column1 string
	Column2 string
	Column3 string
	Column4 string
}

func (q *Queries) CountSearchResults(ctx context.Context, arg CountSearchResultsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchResults,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createBook = `-- name: CreateBook :one
INSERT INTO books (title, subtitle, author, publisher, published_date, isbn10, isbn13, pages, language, description, series_name, series_position, genres, tags, image_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, title, subtitle, author, publisher, published_date, isbn10, isbn13, pages, language, description, series_name, series_position, genres, tags, image_url, created_at, updated_at
`

type CreateBookParams struct {
	Title          string
	Subtitle       *string
	Author         string
	Publisher      *string
	PublishedDate  *time.Time
	Isbn10         *string
	Isbn13         *string
	Pages          *int32
	Language       *string
	Description    *string
	SeriesName     *string
	SeriesPosition *int32
	Genres         *string
	Tags           *string
	ImageUrl       *string
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, createBook,
		arg.Title,
		arg.Subtitle,
		arg.Author,
		arg.Publisher,
		arg.PublishedDate,
		arg.Isbn10,
		arg.Isbn13,
		arg.Pages,
		arg.Language,
		arg.Description,
		arg.SeriesName,
		arg.SeriesPosition,
		arg.Genres,
		arg.Tags,
		arg.ImageUrl,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Subtitle,
		&i.Author,
		&i.Publisher,
		&i.PublishedDate,
		&i.Isbn10,
		&i.Isbn13,
		&i.Pages,
		&i.Language,
		&i.Description,
		&i.SeriesName,
		&i.SeriesPosition,
		&i.Genres,
		&i.Tags,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM books WHERE id = $1
`

func (q *Queries) DeleteBook(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBook, id)
	return err
}

const getBookByID = `-- name: GetBookByID :one
SELECT id, title, subtitle, author, publisher, published_date, isbn10, isbn13, pages, language, description, series_name, series_position, genres, tags, image_url, created_at, updated_at
FROM books
WHERE id = $1
`

func (q *Queries) GetBookByID(ctx context.Context, id uuid.UUID) (Book, error) {
	row := q.db.QueryRow(ctx, getBookByID, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Subtitle,
		&i.Author,
		&i.Publisher,
		&i.PublishedDate,
		&i.Isbn10,
		&i.Isbn13,
		&i.Pages,
		&i.Language,
		&i.Description,
		&i.SeriesName,
		&i.SeriesPosition,
		&i.Genres,
		&i.Tags,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBooksByAuthor = `-- name: GetBooksByAuthor :many
SELECT id, title, subtitle, author, publisher, published_date, isbn10, isbn13, pages, language, description, series_name, series_position, genres, tags, image_url, created_at, updated_at
FROM books
WHERE author = $1
ORDER BY published_date DESC
`

func (q *Queries) GetBooksByAuthor(ctx context.Context, author string) ([]Book, error) {
	rows, err := q.db.Query(ctx, getBooksByAuthor, author)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Subtitle,
			&i.Author,
			&i.Publisher,
			&i.PublishedDate,
			&i.Isbn10,
			&i.Isbn13,
			&i.Pages,
			&i.Language,
			&i.Description,
			&i.SeriesName,
			&i.SeriesPosition,
			&i.Genres,
			&i.Tags,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBooksByISBN13 = `-- name: GetBooksByISBN13 :one
SELECT id, title, subtitle, author, publisher, published_date, isbn10, isbn13, pages, language, description, series_name, series_position, genres, tags, image_url, created_at, updated_at
FROM books
WHERE isbn13 = $1
`

func (q *Queries) GetBooksByISBN13(ctx context.Context, isbn13 *string) (Book, error) {
	row := q.db.QueryRow(ctx, getBooksByISBN13, isbn13)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Subtitle,
		&i.Author,
		&i.Publisher,
		&i.PublishedDate,
		&i.Isbn10,
		&i.Isbn13,
		&i.Pages,
		&i.Language,
		&i.Description,
		&i.SeriesName,
		&i.SeriesPosition,
		&i.Genres,
		&i.Tags,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBooksBySeries = `-- name: GetBooksBySeries :many
SELECT id, title, subtitle, author, publisher, published_date, isbn10, isbn13, pages, language, description, series_name, series_position, genres, tags, image_url, created_at, updated_at
FROM books
WHERE series_name = $1
ORDER BY series_position ASC
`

func (q *Queries) GetBooksBySeries(ctx context.Context, seriesName *string) ([]Book, error) {
	rows, err := q.db.Query(ctx, getBooksBySeries, seriesName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Subtitle,
			&i.Author,
			&i.Publisher,
			&i.PublishedDate,
			&i.Isbn10,
			&i.Isbn13,
			&i.Pages,
			&i.Language,
			&i.Description,
			&i.SeriesName,
			&i.SeriesPosition,
			&i.Genres,
			&i.Tags,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeriesByName = `-- name: GetSeriesByName :one
SELECT 
  series_name as name,
  COUNT(*) as book_count
FROM books
WHERE series_name = $1
GROUP BY series_name
`

type GetSeriesByNameRow struct {
	Name      *string
	BookCount int64
}

func (q *Queries) GetSeriesByName(ctx context.Context, seriesName *string) (GetSeriesByNameRow, error) {
	row := q.db.QueryRow(ctx, getSeriesByName, seriesName)
	var i GetSeriesByNameRow
	err := row.Scan(&i.Name, &i.BookCount)
	return i, err
}

const listAuthors = `-- name: ListAuthors :many
SELECT DISTINCT author
FROM books
ORDER BY author
`

func (q *Queries) ListAuthors(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var author string
		if err := rows.Scan(&author); err != nil {
			return nil, err
		}
		items = append(items, author)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooks = `-- name: ListBooks :many
SELECT id, title, subtitle, author, publisher, published_date, isbn10, isbn13, pages, language, description, series_name, series_position, genres, tags, image_url, created_at, updated_at
FROM books
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListBooksParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListBooks(ctx context.Context, arg ListBooksParams) ([]Book, error) {
	rows, err := q.db.Query(ctx, listBooks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Subtitle,
			&i.Author,
			&i.Publisher,
			&i.PublishedDate,
			&i.Isbn10,
			&i.Isbn13,
			&i.Pages,
			&i.Language,
			&i.Description,
			&i.SeriesName,
			&i.SeriesPosition,
			&i.Genres,
			&i.Tags,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeries = `-- name: ListSeries :many
SELECT 
  DISTINCT series_name as name,
  COUNT(*) as book_count
FROM books
WHERE series_name IS NOT NULL
GROUP BY series_name
ORDER BY series_name
`

type ListSeriesRow struct {
	Name      *string
	BookCount int64
}

func (q *Queries) ListSeries(ctx context.Context) ([]ListSeriesRow, error) {
	rows, err := q.db.Query(ctx, listSeries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeriesRow
	for rows.Next() {
		var i ListSeriesRow
		if err := rows.Scan(&i.Name, &i.BookCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAuthors = `-- name: SearchAuthors :many
SELECT DISTINCT author
FROM books
WHERE author ILIKE '%' || $1 || '%'
ORDER BY author
`

func (q *Queries) SearchAuthors(ctx context.Context, dollar_1 *string) ([]string, error) {
	rows, err := q.db.Query(ctx, searchAuthors, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var author string
		if err := rows.Scan(&author); err != nil {
			return nil, err
		}
		items = append(items, author)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBooks = `-- name: SearchBooks :many
SELECT id, title, subtitle, author, publisher, published_date, isbn10, isbn13, pages, language, description, series_name, series_position, genres, tags, image_url, created_at, updated_at
FROM books
WHERE 
  ($1::text IS NULL OR title ILIKE '%' || $1 || '%')
  AND ($2::text IS NULL OR author ILIKE '%' || $2 || '%')
  AND ($3::text IS NULL OR publisher ILIKE '%' || $3 || '%')
  AND ($4::text IS NULL OR series_name ILIKE '%' || $4 || '%')
ORDER BY 
  CASE 
    WHEN $5 = 'title' THEN title
    WHEN $5 = 'author' THEN author
    WHEN $5 = 'published_date' THEN published_date::text
    WHEN $5 = 'created_at' THEN created_at::text
  END,
  created_at DESC
LIMIT $6 OFFSET $7
`

type SearchBooksParams struct {
	Column1 string
	Column2 string
	Column3 string
	Column4 string
	Column5 interface{}
	Limit   int32
	Offset  int32
}

func (q *Queries) SearchBooks(ctx context.Context, arg SearchBooksParams) ([]Book, error) {
	rows, err := q.db.Query(ctx, searchBooks,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Subtitle,
			&i.Author,
			&i.Publisher,
			&i.PublishedDate,
			&i.Isbn10,
			&i.Isbn13,
			&i.Pages,
			&i.Language,
			&i.Description,
			&i.SeriesName,
			&i.SeriesPosition,
			&i.Genres,
			&i.Tags,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBook = `-- name: UpdateBook :exec
UPDATE books
SET title = $1, subtitle = $2, author = $3, publisher = $4, published_date = $5, isbn10 = $6, isbn13 = $7, pages = $8, language = $9, description = $10, series_name = $11, series_position = $12, genres = $13, tags = $14, image_url = $15
WHERE id = $16
`

type UpdateBookParams struct {
	Title          string
	Subtitle       *string
	Author         string
	Publisher      *string
	PublishedDate  *time.Time
	Isbn10         *string
	Isbn13         *string
	Pages          *int32
	Language       *string
	Description    *string
	SeriesName     *string
	SeriesPosition *int32
	Genres         *string
	Tags           *string
	ImageUrl       *string
	ID             uuid.UUID
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) error {
	_, err := q.db.Exec(ctx, updateBook,
		arg.Title,
		arg.Subtitle,
		arg.Author,
		arg.Publisher,
		arg.PublishedDate,
		arg.Isbn10,
		arg.Isbn13,
		arg.Pages,
		arg.Language,
		arg.Description,
		arg.SeriesName,
		arg.SeriesPosition,
		arg.Genres,
		arg.Tags,
		arg.ImageUrl,
		arg.ID,
	)
	return err
}
