// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Book struct {
	ID             uuid.UUID
	Title          string
	Subtitle       *string
	Author         string
	Publisher      *string
	PublishedDate  *time.Time
	Isbn10         *string
	Isbn13         *string
	Pages          *int32
	Language       *string
	Description    *string
	SeriesName     *string
	SeriesPosition *int32
	Genres         *string
	Tags           *string
	ImageUrl       *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
