// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: publishers.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPublishers = `-- name: CountPublishers :one
SELECT COUNT(*) FROM publishers
`

func (q *Queries) CountPublishers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPublisher = `-- name: CreatePublisher :one
INSERT INTO publishers (name, slug, website)
VALUES ($1, $2, $3)
RETURNING id, name, slug, website, created_at, updated_at
`

type CreatePublisherParams struct {
	Name    string
	Slug    *string
	Website *string
}

func (q *Queries) CreatePublisher(ctx context.Context, arg CreatePublisherParams) (Publisher, error) {
	row := q.db.QueryRow(ctx, createPublisher, arg.Name, arg.Slug, arg.Website)
	var i Publisher
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Website,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePublisher = `-- name: DeletePublisher :exec
DELETE FROM publishers WHERE id = $1
`

func (q *Queries) DeletePublisher(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePublisher, id)
	return err
}

const getPublisherBookCount = `-- name: GetPublisherBookCount :one
SELECT COUNT(*) FROM books WHERE publisher_id = $1
`

func (q *Queries) GetPublisherBookCount(ctx context.Context, publisherID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getPublisherBookCount, publisherID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPublisherByID = `-- name: GetPublisherByID :one
SELECT id, name, slug, website, created_at, updated_at FROM publishers WHERE id = $1
`

func (q *Queries) GetPublisherByID(ctx context.Context, id uuid.UUID) (Publisher, error) {
	row := q.db.QueryRow(ctx, getPublisherByID, id)
	var i Publisher
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Website,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublisherByName = `-- name: GetPublisherByName :one
SELECT id, name, slug, website, created_at, updated_at FROM publishers WHERE name = $1
`

func (q *Queries) GetPublisherByName(ctx context.Context, name string) (Publisher, error) {
	row := q.db.QueryRow(ctx, getPublisherByName, name)
	var i Publisher
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Website,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublisherBySlug = `-- name: GetPublisherBySlug :one
SELECT id, name, slug, website, created_at, updated_at FROM publishers WHERE slug = $1
`

func (q *Queries) GetPublisherBySlug(ctx context.Context, slug *string) (Publisher, error) {
	row := q.db.QueryRow(ctx, getPublisherBySlug, slug)
	var i Publisher
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Website,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublishers = `-- name: ListPublishers :many
SELECT id, name, slug, website, created_at, updated_at FROM publishers
ORDER BY name
LIMIT $1 OFFSET $2
`

type ListPublishersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListPublishers(ctx context.Context, arg ListPublishersParams) ([]Publisher, error) {
	rows, err := q.db.Query(ctx, listPublishers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Publisher
	for rows.Next() {
		var i Publisher
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Website,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPublishers = `-- name: SearchPublishers :many
SELECT id, name, slug, website, created_at, updated_at FROM publishers
WHERE name ILIKE '%' || $1 || '%'
ORDER BY name
LIMIT $2 OFFSET $3
`

type SearchPublishersParams struct {
	Column1 *string
	Limit   int32
	Offset  int32
}

func (q *Queries) SearchPublishers(ctx context.Context, arg SearchPublishersParams) ([]Publisher, error) {
	rows, err := q.db.Query(ctx, searchPublishers, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Publisher
	for rows.Next() {
		var i Publisher
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Website,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePublisher = `-- name: UpdatePublisher :one
UPDATE publishers
SET name = $2, slug = $3, website = $4, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, slug, website, created_at, updated_at
`

type UpdatePublisherParams struct {
	ID      uuid.UUID
	Name    string
	Slug    *string
	Website *string
}

func (q *Queries) UpdatePublisher(ctx context.Context, arg UpdatePublisherParams) (Publisher, error) {
	row := q.db.QueryRow(ctx, updatePublisher,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Website,
	)
	var i Publisher
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Website,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
