// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: series.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countSeries = `-- name: CountSeries :one
SELECT COUNT(*) FROM series
`

func (q *Queries) CountSeries(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSeries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSeries = `-- name: CreateSeries :one
INSERT INTO series (name, slug, description)
VALUES ($1, $2, $3)
RETURNING id, name, slug, description, created_at, updated_at
`

type CreateSeriesParams struct {
	Name        string
	Slug        *string
	Description *string
}

func (q *Queries) CreateSeries(ctx context.Context, arg CreateSeriesParams) (Series, error) {
	row := q.db.QueryRow(ctx, createSeries, arg.Name, arg.Slug, arg.Description)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSeries = `-- name: DeleteSeries :exec
DELETE FROM series WHERE id = $1
`

func (q *Queries) DeleteSeries(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSeries, id)
	return err
}

const getSeriesBookCount = `-- name: GetSeriesBookCount :one
SELECT COUNT(*) FROM books WHERE series_id = $1
`

func (q *Queries) GetSeriesBookCount(ctx context.Context, seriesID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getSeriesBookCount, seriesID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSeriesByID = `-- name: GetSeriesByID :one
SELECT id, name, slug, description, created_at, updated_at FROM series WHERE id = $1
`

func (q *Queries) GetSeriesByID(ctx context.Context, id uuid.UUID) (Series, error) {
	row := q.db.QueryRow(ctx, getSeriesByID, id)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSeriesByName = `-- name: GetSeriesByName :one
SELECT id, name, slug, description, created_at, updated_at FROM series WHERE name = $1
`

func (q *Queries) GetSeriesByName(ctx context.Context, name string) (Series, error) {
	row := q.db.QueryRow(ctx, getSeriesByName, name)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSeriesBySlug = `-- name: GetSeriesBySlug :one
SELECT id, name, slug, description, created_at, updated_at FROM series WHERE slug = $1
`

func (q *Queries) GetSeriesBySlug(ctx context.Context, slug *string) (Series, error) {
	row := q.db.QueryRow(ctx, getSeriesBySlug, slug)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSeries = `-- name: ListSeries :many
SELECT id, name, slug, description, created_at, updated_at FROM series
ORDER BY name
LIMIT $1 OFFSET $2
`

type ListSeriesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListSeries(ctx context.Context, arg ListSeriesParams) ([]Series, error) {
	rows, err := q.db.Query(ctx, listSeries, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Series
	for rows.Next() {
		var i Series
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSeries = `-- name: SearchSeries :many
SELECT id, name, slug, description, created_at, updated_at FROM series
WHERE name ILIKE '%' || $1 || '%'
ORDER BY name
LIMIT $2 OFFSET $3
`

type SearchSeriesParams struct {
	Column1 *string
	Limit   int32
	Offset  int32
}

func (q *Queries) SearchSeries(ctx context.Context, arg SearchSeriesParams) ([]Series, error) {
	rows, err := q.db.Query(ctx, searchSeries, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Series
	for rows.Next() {
		var i Series
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSeries = `-- name: UpdateSeries :one
UPDATE series
SET name = $2, slug = $3, description = $4, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, slug, description, created_at, updated_at
`

type UpdateSeriesParams struct {
	ID          uuid.UUID
	Name        string
	Slug        *string
	Description *string
}

func (q *Queries) UpdateSeries(ctx context.Context, arg UpdateSeriesParams) (Series, error) {
	row := q.db.QueryRow(ctx, updateSeries,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
